Repository vmware/ansible-for-nsxt, pull requests merged in 2020-04, with the labels that each got.

#254 Fix optional address_pool in Segment
  library/nsxt_policy_segment.py
Labels: bug, dco-required

#256 Fix optional address_pool in Segment
  library/nsxt_policy_segment.py
Labels: bug

#255 Update example vars file
  examples/deploy_nsx_cluster/04_add_nsx_license.yml
  examples/deploy_nsx_cluster/deploy_nsx_cluster_vars.yml
  examples/misc/create_and_attach_t0_t1_routers.yml
  examples/policy_modules/build_topology_vars.yml
Labels: dco-required

#260 Gracefully exit upon unexpected error from Manager
  module_utils/nsxt_base_resource.py
  module_utils/policy_communicator.py
Labels: dco-required
