Repository vmware/ansible-for-nsxt, pull requests merged in 2020-03, with the labels that each got.

#189 Add missing attrs in policy_group and securty_policy
  policy-ansible-for-nsxt/library/nsxt_policy_group.py
  policy-ansible-for-nsxt/library/nsxt_security_policy.py
Labels: dco-required, enhancement

#158 Add support for vrf_config in tier0
  policy-ansible-for-nsxt/README.md
  policy-ansible-for-nsxt/library/nsxt_tier0.py
  policy-ansible-for-nsxt/module_utils/nsxt_base_resource.py
  policy-ansible-for-nsxt/unit_tests/test_nsxt_tier0.yml
Labels: enhancement

#191 Add missing attrs in nsxt_segment and seg_ports
  policy-ansible-for-nsxt/library/nsxt_segment.py
  policy-ansible-for-nsxt/module_utils/nsxt_base_resource.py
  policy-ansible-for-nsxt/unit_tests/test_nsxt_segment.yml
Labels: enhancement

#194 Add missing attrs in tier0
  policy-ansible-for-nsxt/library/nsxt_tier0.py
  policy-ansible-for-nsxt/unit_tests/test_nsxt_tier0.yml
Labels: dco-required, enhancement

#195 Add missing attrs in tier1 module
  policy-ansible-for-nsxt/library/nsxt_tier1.py
  policy-ansible-for-nsxt/unit_tests/test_nsxt_tier0.yml
  policy-ansible-for-nsxt/unit_tests/test_nsxt_tier1.yml
Labels: enhancement

#197 Add missing attrs in nsxt_segment
  policy-ansible-for-nsxt/library/nsxt_segment.py
  policy-ansible-for-nsxt/unit_tests/test_nsxt_segment.yml
Labels: enhancement

#196 Add missing attrs for rules in security_policy
  policy-ansible-for-nsxt/library/nsxt_security_policy.py
  policy-ansible-for-nsxt/unit_tests/test_nsxt_security_policy.yml
Labels: enhancement

#157 Add support for T0 BFD Peer & Config
  policy-ansible-for-nsxt/library/nsxt_bfd_config.py
  policy-ansible-for-nsxt/library/nsxt_tier0.py
  policy-ansible-for-nsxt/module_utils/nsxt_base_resource.py
  policy-ansible-for-nsxt/module_utils/nsxt_resource_urls.py
  policy-ansible-for-nsxt/unit_tests/test_bfd_config.yaml
  policy-ansible-for-nsxt/unit_tests/test_nsxt_tier0.yml
Labels: enhancement

#156 Add Module to allow VM Tags Update
  policy-ansible-for-nsxt/library/nsxt_vm_tags.py
  policy-ansible-for-nsxt/module_utils/nsxt_resource_urls.py
  policy-ansible-for-nsxt/unit_tests/test_vm_tags.yaml
Labels: dco-required, enhancement

#202 TN examples updated
  answerfile.yml
  test_transport_nodes_edge.yml
  test_transport_nodes_host.yml
Labels: dco-required

#203 Principal identity used deprecated API
  library/nsxt_principal_identities.py
Labels: dco-required

#200 Add support to use Principal Identity and headers
  policy-ansible-for-nsxt/README.md
  policy-ansible-for-nsxt/library/nsxt_bfd_config.py
  policy-ansible-for-nsxt/library/nsxt_ip_block.py
  policy-ansible-for-nsxt/library/nsxt_ip_pool.py
  policy-ansible-for-nsxt/library/nsxt_policy_group.py
  policy-ansible-for-nsxt/library/nsxt_security_policy.py
  policy-ansible-for-nsxt/library/nsxt_segment.py
  policy-ansible-for-nsxt/library/nsxt_tier0.py
  policy-ansible-for-nsxt/library/nsxt_tier1.py
  policy-ansible-for-nsxt/library/nsxt_vm_tags.py
  policy-ansible-for-nsxt/module_utils/nsxt_base_resource.py
  policy-ansible-for-nsxt/module_utils/policy_communicator.py
  policy-ansible-for-nsxt/plugins/doc_fragments/vmware_nsxt.py
  policy-ansible-for-nsxt/tests/unit/module_utils/test_nsxt_base_resource.py
  policy-ansible-for-nsxt/unit_tests/test_bfd_config.yaml
  policy-ansible-for-nsxt/unit_tests/test_nsxt_ip_block.yml
  policy-ansible-for-nsxt/unit_tests/test_nsxt_ip_pool.yml
  policy-ansible-for-nsxt/unit_tests/test_nsxt_policy_group.yml
  policy-ansible-for-nsxt/unit_tests/test_nsxt_security_policy.yml
  policy-ansible-for-nsxt/unit_tests/test_nsxt_segment.yml
  policy-ansible-for-nsxt/unit_tests/test_nsxt_tier0.yml
  policy-ansible-for-nsxt/unit_tests/test_nsxt_tier1.yml
  policy-ansible-for-nsxt/unit_tests/test_vm_tags.yaml
Labels: enhancement

#209 Adding facts module for Principal Identities and Certificate
  library/nsxt_certificates_facts.py
  library/nsxt_principal_identities.py
  library/nsxt_principal_identities_facts.py
  test_certificates_facts.yml
  test_principal_identities_facts.yml
Labels: dco-required

#208 Improving example of transport node
  answerfile.yml
  test_transport_nodes.yml
Labels: dco-required

#215 Adding optional params to TN module and edge cluster
  library/nsxt_edge_clusters.py
  library/nsxt_transport_nodes.py
Labels: dco-required

#223 Add support for .p12 certificate
  README.md
  module_utils/policy_communicator.py
Labels: enhancement

#239 Update locale_service attr per policy API change
  library/nsxt_policy_tier0.py
Labels: bug, dco-required
